dist: trusty
language: java
jdk: oraclejdk9
env:
  - COVERAGE=$COVERAGE _VALUE ./gradlew test jacocoTestCoverageVerification

before_script:
  - ./gradlew clean jar
  #- echo "testing coming soon"

script:
  - ./gradlew test
after_success:
    - ./gradlew jacocoTestReport
    - find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'
    - ./gradlew jacocoTestCoverageVerification
deploy:
    provider: script
    script: echo 'WIP'
    on:
      all_branches: true
  # Run ANSIBLE checks
  # - ANSIBLE0008: Disabled for use of sudo warnings - to address
  # - ANSIBLE0011: Disabled for all tasks which should be named
  # - ANSIBLE0012: Disabled (should not change if nothings needs doing) - to address
  # - ANSIBLE0013: Disabled - few uses of shell commands - to address
  #- find vagrant/provision -name "*.yml" -exec ansible-lint -x ANSIBLE008,ANSIBLE0011,ANSIBLE0012,ANSIBLE0013  {} +
